### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by krmbzds** [st0012/mini-debugger#1]
Hello Stan,

This mini-debugger made my day and it was an absolute joy to play with.

I just wanted to take a moment to express my gratitude for your work on improving Ruby debugging tools. Your contributions have truly made a difference and I wanted to let you know how much I appreciate it. Thank you again for your hard work and dedication. Your contribution to the Ruby ecosystem is invaluable.

Best, :sun_with_face: 
Kerem

**Comment by st0012** [comment]
@krmbzds Thank you so much for the kind words, it really means a lot to me 🙏
